-- 코드를 작성해주세요

-- select 노선별, 총 누계거리(sum - D_BETWEEN_DIST), 평균 역사이 거리 
-- group by 노선별 


SELECT      ROUTE AS ROUTE
            ,CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),'km') AS TOTAL_DISTANCE
            ,CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),'km') AS AVERAGE_DISTANCE

FROM        SUBWAY_DISTANCE
GROUP BY    ROUTE
ORDER BY    SUM(D_BETWEEN_DIST) DESC

# SELECT
#     ROUTE,
#     CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE,
#     CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
# FROM SUBWAY_DISTANCE
# GROUP BY ROUTE
# ORDER BY SUM(D_BETWEEN_DIST) DESC;