name: dispatch_action

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_PAT }}
          repository: meanresult/programmers-badge-v1
          event-type: trigger-workflow
